// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcu1AdUhXZ4fppGV4LhVfudouU7BHROe4',
    appId: '1:31394036532:web:2cb63b0d6aed62f66ac361',
    messagingSenderId: '31394036532',
    projectId: 'covoiturage-4f60b',
    authDomain: 'covoiturage-4f60b.firebaseapp.com',
    storageBucket: 'covoiturage-4f60b.firebasestorage.app',
    measurementId: 'G-21MN4XXVD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgbrAGVj1-wb0Ojj8Sto3cykr7spl6Spc',
    appId: '1:31394036532:android:2596e25e9a6560a36ac361',
    messagingSenderId: '31394036532',
    projectId: 'covoiturage-4f60b',
    storageBucket: 'covoiturage-4f60b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTfVr8tMAJVjI06ARaLUkpykIXfB0HJr4',
    appId: '1:31394036532:ios:bcf165fdd7c834356ac361',
    messagingSenderId: '31394036532',
    projectId: 'covoiturage-4f60b',
    storageBucket: 'covoiturage-4f60b.firebasestorage.app',
    iosBundleId: 'com.example.covoiturage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTfVr8tMAJVjI06ARaLUkpykIXfB0HJr4',
    appId: '1:31394036532:ios:bcf165fdd7c834356ac361',
    messagingSenderId: '31394036532',
    projectId: 'covoiturage-4f60b',
    storageBucket: 'covoiturage-4f60b.firebasestorage.app',
    iosBundleId: 'com.example.covoiturage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcu1AdUhXZ4fppGV4LhVfudouU7BHROe4',
    appId: '1:31394036532:web:b65a57ad144090b16ac361',
    messagingSenderId: '31394036532',
    projectId: 'covoiturage-4f60b',
    authDomain: 'covoiturage-4f60b.firebaseapp.com',
    storageBucket: 'covoiturage-4f60b.firebasestorage.app',
    measurementId: 'G-1XYQXBQBQY',
  );
}
